CREATE TABLE public.products (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	created_at timestamptz(6) NOT NULL,
	updated_at timestamptz(6) NULL,
	"version" int8 NULL,
	active bool NOT NULL,
	description varchar(1000) NULL,
	"name" varchar(255) NOT NULL,
	price numeric(15, 2) NOT NULL,
	stock int4 NOT NULL,
	CONSTRAINT products_pkey PRIMARY KEY (id)
);
