spring.application.name=payment-service

server.port=0

# gRPC port
grpc.server.port=6565

# Kafka config
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer

# Actuator health
management.endpoints.web.exposure.include=health,info
management.endpoint.health.probes.enabled=true
