spring.application.name=Product and Order Service
server.port=8080

#database
spring.datasource.url=jdbc:postgresql://localhost:5432/ecommerce
spring.datasource.username=postgres
spring.datasource.password=password